# Production deployment analysis configuration
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable rules that cause build failures
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_declarations: false
    sized_box_for_whitespace: false
    avoid_renaming_method_parameters: false

# Treat warnings as non-fatal
analyzer:
  errors:
    unused_import: warning
    unused_element: warning
    unused_local_variable: warning
    deprecated_member_use: info
    unnecessary_import: warning
