name: asim_platform
description: Cross-platform eSIM application connecting users to global data plans
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  material_color_utilities: ^0.11.1
  go_router: ^12.1.3
  
  # Internationalization
  intl: ^0.19.0
  
  # State Management
  provider: ^6.1.1
  
  # Network & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Payment Integration
  pay: ^1.1.0
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Utils
  url_launcher: ^6.2.2
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.2
  
  # Image & File handling
  image_picker: ^1.0.4
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/flags/
